<?php $baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>
<?php $baseUrl .= 'product/' ?>

    <!-- FOOTER PICTURE LINKS -->
	<table cellspacing="0" cellpadding="0" border="0">
      <tbody><tr>
       <td><a href="<?php echo $baseUrl . 'affiliates' ?>"><img border="0" alt="shipping" src="<?php echo $this->getSkinUrl('images/footer_free_shipping.jpg') ?>"/></a></td>
       <td width="2"><img src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>"/></td>
       <td><a href="<?php echo $baseUrl . 'new/products' ?>"><img border="0" alt="What's New" src="<?php echo $this->getSkinUrl('images/footer_whats_new.jpg') ?>"/></a></td>
       <td width="2"><img src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>"/></td>
       <td><a href="<?php echo $baseUrl . 'bestsellers/all' ?>"><img border="0" alt="Bestsellers" src="<?php echo $this->getSkinUrl('images/footer_bestsellers.jpg') ?>"/></a></td>
       <td width="2"><img src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>"/></td>
       <td><a href="http://www.nimlitalk.com/"><img border="0" alt="Nimli Talk" src="<?php echo $this->getSkinUrl('images/footer_blog.jpg') ?>"/></a></td>
       <td width="2"><img src="<?php echo $this->getSkinUrl('images/spacer.gif') ?>"/></td>
       <td><img border="0" alt="Networks" src="<?php echo $this->getSkinUrl('images/footer_networks.jpg') ?>" usemap="#networks"/><map name="networks"><area shape="rect" coords="35,26,68,61" alt="Sun" href="" /><area shape="rect" coords="78,26,113,61" alt="Sun" href="" /></map></td>
      </tr>
    </tbody></table>
    <!-- END FOOTER PICTURE LINKS -->