<?php
$url = Mage::app()->getStore()->getBaseUrl();
?>
<div class="left_column_content">

<div><a href="<?php echo $url . ''; ?>">By Occasion</a></div>
<div><a href="<?php echo $url . ''; ?>">By Recipient</a></div>
<div><a href="<?php echo $url . ''; ?>">Corporate Gifts</a></div>
<div><a href="<?php echo $url . ''; ?>">Gift Certificates</a></div>

</div>
<div style="padding: 5px 0px; margin-top: 5px; border-top: 1px solid #DDD"></div>