<td valign="top" align="left"><b>currency:</b></td> 
                <td valign="top" align="left"> 
						<a href="<?php echo $this->getSwitchCurrencyUrl('USD') ?>"> 
						  <img src="<?php echo $this->getSkinUrl('images/flag_us.gif') ?>" alt="" border="0" class="flagBorder selected" /> 
						</a> 
						<a href="<?php echo $this->getSwitchCurrencyUrl('CAD') ?>"> 
						  <img src="<?php echo $this->getSkinUrl('images/flag_ca.gif') ?>" alt="" border="0" class="flagBorder" /> 
						</a> 
						<a href="<?php echo $this->getSwitchCurrencyUrl('EUR') ?>"> 
						  <img src="<?php echo $this->getSkinUrl('images/flag_eu.gif') ?>" alt="" border="0" class="flagBorder" /> 
						</a> 
						<a href="<?php echo $this->getSwitchCurrencyUrl('GBP') ?>"> 
						  <img src="<?php echo $this->getSkinUrl('images/flag_uk.gif') ?>" alt="" border="0" class="flagBorder" /> 
						</a> 
						<a href="<?php echo $this->getSwitchCurrencyUrl('AUD') ?>">
						  <img src="<?php echo $this->getSkinUrl('images/flag_au.gif') ?>" alt="" border="0" class="flagBorder" /> 
						</a> 
						<a href="<?php echo $this->getSwitchCurrencyUrl('JPY') ?>"> 
						  <img src="<?php echo $this->getSkinUrl('images/flag_ja.gif') ?>" alt="" border="0" class="flagBorder" /> 
						</a> 
					 
 
            	</td> 

